languageCode = "en-us"
title = "Open Source Club"
description = "At The Ohio State University"
theme = "kube"
paginate = 15

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Events"
    url = "/events"

[params]
    # Use this to display a message on  the home page
    message = "Biweekly meetings on Thursdays, 6:30 PM in Enarson 248"

    twitter = "osuosc"
    github = "OSUOSC"
